files:
  - source: themes/src/main/resources/theme/base/admin/**/admin-messages_en.properties
    translation: '%original_path%/admin-messages_%two_letters_code%.properties'
  - source: themes/src/main/resources/theme/base/admin/**/messages_en.properties
    translation: '%original_path%/messages_%two_letters_code%.properties'
