files:
  - source: admin-messages_en.properties
    translation: '%original_path%/admin-messages_%two_letters_code%.properties'
  - source: messages_en.properties
    translation: '%original_path%/messages_%two_letters_code%.properties'
